version: 0.2

phases:
  pre_build:
    commands:
      - echo "Autenticando con Amazon ECR..."
      - $(aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com)
  build:
    commands:
      - echo "Construyendo la imagen Docker..."
      - docker build -t flask-api .
      - docker tag flask-api:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/flask-api:latest
  post_build:
    commands:
      - echo "Subiendo la imagen a Amazon ECR..."
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/flask-api:latest
      - echo "Desplegando con AWS SAM..."
      - sam deploy --template-file template.yaml --stack-name flask-api --capabilities CAPABILITY_IAM
